assert "MAX_RAM_MB" in config, "'MAX_RAM_MB' not in config"
assert "MAX_THREADS" in config, "'MAX_THREADS' not in config"
assert "MAX_VRAM_MB" in config, "'MAX_VRAM_MB' not in config"
MAX_RAM_MB = config["MAX_RAM_MB"]
MAX_THREADS = config["MAX_THREADS"]
MAX_VRAM_MB = config["MAX_VRAM_MB"]

SEQS = []

class DenovoSequencing():
    def __init__(self, 
                project, #name of your project
                MS_data, #path to the folder with MS data (.mzML)
                genome, #name of your genome that you generated with IndexGenome.jar
                model='casanovo_nontryptic.ckpt', #name of your Casanovo model file
                extra=None, #Fasta file containing extra sequences (DNA will be 6-frame translated!)!
                rnaseq=None, #Fasta file containing extra transcript sequences (will be 3-frame translated!)!
                var=None #File containing variants (each line); could also be in ${input%.csv}.var, in which case you do not have to specify this parameter!
                ):
        self.project = project 
        self.MS_data = MS_data 
        self.genome = genome 
        self.model = model
        self.extra = extra 
        self.rnaseq = rnaseq 
        self.var = var 

if "todo" in config:
    include: f"profiles/{config['todo']}/todo.py"

def get_dataset(project):
    for dataset in SEQS:
        if dataset.project == project:
            return dataset
    raise ValueError(f"Dataset {project} not found")

rule all:
    input:
        casanovo_mztab = [f"_data/casanovo/{seq.project}/{seq.project}.mztab" for seq in SEQS]

rule run_Casanovo:
    input:
        MS_data = lambda wildcards: get_dataset(wildcards.project).MS_data
    output:
        mztab = "_data/casanovo/{project}/{project}.mztab"
    singularity:
        "workflow/containers/image/python.3.10.15.gpu.ubuntu.sif"
    params:
        model = lambda wildcards: get_dataset(wildcards.project).model,
    resources:
        vram=MAX_VRAM_MB
    shell:
        '''
        casanovo sequence -o {output.mztab} -m model/{params.model} -c model/config.yaml -v info {input.MS_data}/*.mzML
        '''



#rule postprocessing:



# rule have_fun:
#               __________ 
#              |          |
#              | ~@**#~~  |
#        ,,,   |  ________|
#      (O___0) \/  
#   \    | |    /
#    \ \     \ /
#      /     /
#      |     |